---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: "shared"
            project: "prod"
            branch: "main"
  template:
    metadata:
      name: "jupyterhub-{{ project }}"
      namespace: argocd
    spec:
      project: "{{ project }}"
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - chart: jupyterhub
          repoURL: https://hub.jupyter.org/helm-chart/ # Must be a Helm repository
          targetRevision: "4.1.0" # Version of the chart
          helm:
            releaseName: "jupyterhub-{{ namespace }}"
            valueFiles:
              - $values/components/jupyterhub-chart/values.ref.yaml # One global values file
              - $values/components/jupyterhub-chart/values.{{ project }}.yaml
        - repoURL: "https://github.com/confianceai/reference-environment.git" # to Do not forget '.git'
          targetRevision: "{{ branch }}" # Git repository branch
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ namespace }}"
