crds:
  enabled: true
  keep: true

extraArgs:
  - --enable-certificate-owner-ref=true
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53

resources:
  requests:
    cpu: 25m
    memory: 50Mi
  limits:
    cpu: 50m
    memory: 150Mi
