# Default values for metallb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets:
  - name: regcred

# controller contains configuration specific to the MetalLB cluster
# controller.
controller:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 100Mi

# speaker contains configuration specific to the MetalLB speaker
# daemonset.
speaker:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
  # frr contains configuration specific to the MetalLB FRR container,
  # for speaker running alongside FRR.
  frr:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 100Mi

    # if set, enables a rbac proxy sidecar container on the speaker to
    # expose the frr metrics via tls.
    # secureMetricsPort: 9121

  reloader:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi

  frrMetrics:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
