---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: "shared"
            project: "prod"
            branch: "main"
  template:
    metadata:
      name: "argo-workflows-{{ project }}"
      namespace: argocd
    spec:
      project: "{{ project }}"
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - chart: argo-workflows
          repoURL: https://argoproj.github.io/argo-helm
          targetRevision: 0.45.1 # Version of the chart
          helm:
            releaseName: argo-workflows
            valueFiles:
              - $values/components/argo-workflows-chart/values.ref.yaml # One global values file
              - $values/components/argo-workflows-chart/values.{{ project }}.yaml # One values file per environment, potentially containing secrets references with vals
        - repoURL: "https://github.com/confianceai/reference-environment.git" # Do not forget '.git'
          targetRevision: "{{ branch }}" # Git repository branch
          ref: values
        - repoURL: "https://github.com/confianceai/reference-environment.git"
          directory:
            include: "{*.role.yaml,*.cwt.yaml}" # Deploy all .role.yaml files
          path: components/argo-workflows-chart
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ namespace }}"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-workflows-pg
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: "shared"
            project: "prod"
            branch: "main"
  template:
    metadata:
      name: "argo-workflows-pg-{{ project }}"
      namespace: argocd
    spec:
      project: "{{ project }}"
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - chart: postgresql
          repoURL: https://charts.bitnami.com/bitnami
          targetRevision: 16.2.1 # Version of the chart
          helm:
            releaseName: argo-workflows-pg
            valueFiles:
              - $values/components/argo-workflows-chart/values-pg.ref.yaml # One global values file
              - $values/components/argo-workflows-chart/values-pg.{{ project }}.yaml # One values file per environment, potentially containing secrets references with vals
        - repoURL: "https://github.com/confianceai/reference-environment.git" # Do not forget '.git'
          targetRevision: "{{ branch }}" # Git repository branch
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ namespace }}"
